version: 2.1

orbs:
  node: circleci/node@4.1.0
  python: circleci/python@1.2.1
  openjdk-install: cloudesire/openjdk-install@1.2.3

workflows:
  node-tests:
    jobs:
      - node/test:
          name: run-node-tests
          pkg-manager: yarn
          run-command: ci-test
          version: 14.9.0
          cache-version: v3
  python-tests:
    jobs:
      - python/test:
          name: run-ingest-gcf-tests
          app-dir: bfr/ingest-gcf
          args: "--dev"
          pkg-manager: pipenv
          test-tool: pytest
          version: 3.8-node
          setup:
            - openjdk-install
            - run:
                name: Install Firebase CLI
                command: sudo npm install -g firebase-tools
            - run:
                name: Start up Firebase Local Emulator Suite
                command: firebase emulators:start --only firestore
