version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          name: kmgmt-common
          pkg-manager: yarn
          app-dir: kmgmt/kmgmt-common
          cache-version: v2
      - node/test:
          name: kmgmt-app
          pkg-manager: yarn
          app-dir: kmgmt/kmgmt-app
          cache-version: v2
      - node/test:
          name: kmgmt-native-app
          pkg-manager: yarn
          app-dir: kmgmt/kmgmt-native-app
          cache-version: v2
