version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          app-dir: kmgmt/kmgmt-common
      - node/test:
          pkg-manager: yarn
          app-dir: kmgmt/kmgmt-app
      - node/test:
          pkg-manager: yarn
          app-dir: kmgmt/kmgmt-native-app
